name: Argo CD CI/CD

on:
  workflow_run:
    workflows:
      - Terraform CI/CD
    types:
      - completed

  workflow_dispatch:

jobs:
  argocd:
 

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3. Get EKS cluster name
      - name: Get EKS Cluster Name
        id: eks
        run: |
          CLUSTER_NAME=$(aws eks list-clusters \
            --region ap-south-1 \
            --query 'clusters[0]' \
            --output text)

          echo "EKS Cluster: $CLUSTER_NAME"

          if [ "$CLUSTER_NAME" = "None" ] || [ -z "$CLUSTER_NAME" ]; then
            echo "No EKS cluster found in ap-south-1"
            exit 1
          fi

          echo "cluster_name=$CLUSTER_NAME" >> "$GITHUB_OUTPUT"

      # 4. Configure kubectl
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name "${{ steps.eks.outputs.cluster_name }}"

      # 5. Verify EKS
      - name: Verify Kubernetes Cluster
        run: |
          kubectl get nodes

      # 6. Verify Argo CD
      - name: Verify Argo CD
        run: |
          kubectl get pods -n argocd

      # 7. Apply Argo CD Application
      - name: Apply Argo CD Application
        run: |
          kubectl apply -f argocd/application.yaml

      # 8. Verify Argo CD Application
      - name: Verify Argo CD Application
        run: |
          kubectl get application eks-application -n argocd

      # 9. Check application status
      - name: Check Argo CD Application Status
        run: |
          kubectl get application eks-application \
            -n argocd \
            -o wide
