name: Argo CD CI/CD

on:
  workflow_run:
    workflows:
      - Terraform CI/CD
    types:
      - completed

  workflow_dispatch:

jobs:
  argocd:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Get EKS Cluster Name
        id: eks
        run: |
          CLUSTER_NAME=$(aws eks list-clusters \
            --region ap-south-1 \
            --query 'clusters[0]' \
            --output text)

          echo "EKS Cluster: $CLUSTER_NAME"

          if [ "$CLUSTER_NAME" = "None" ] || [ -z "$CLUSTER_NAME" ]; then
            echo "No EKS cluster found in ap-south-1"
            exit 1
          fi

          echo "cluster_name=$CLUSTER_NAME" >> "$GITHUB_OUTPUT"

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name "${{ steps.eks.outputs.cluster_name }}"

      - name: Verify Kubernetes Cluster
        run: |
          kubectl get nodes

      - name: Verify Argo CD
        run: |
          kubectl get pods -n argocd

      - name: Apply Argo CD Application
        run: |
          kubectl apply -f k8s/application.yaml

      - name: Verify Argo CD Application
        run: |
          kubectl get application eks-application -n argocd

      - name: Check Argo CD Application
        run: |
          kubectl get application eks-application \
            -n argocd \
            -o wide
